### PR TITLE
Review

### PR DESCRIPTION
**Pull request by wuehr1999**
Hi @generationmake, @BrixInMotion,

here is the new review pull request...

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @wuehr1999 
I think the hardware emergency stop should be connected to the anode of D3. And there should be a weak pull down on EM_STOP.

And could you add some THT pins on +BATT to get the opportunity to add some big capacitors.

How about adding a diode on the input for reverse polarity protection?

And how about adding a connector for Arduino Nano? https://store.arduino.cc/arduino-nano-33-iot-with-headers

**Comment by wuehr1999** [comment]
Hi @generationmake 

I fixed the emergency stop circuit.

I also added the reverse polarity protection diode and the connector for the Arduino Nano.

Unfortunately, I couldn't find a suitable spot for the THT capacitors. Instead of this I came up with the possibility of mounting 4 big SMD electrolytic capacitors on the bottom layer directly between the supply pins of each half bridge. Is this solution acceptable for You?

**Comment by generationmake** [comment]
Hi @wuehr1999 
the +5V rail should be connected to the VIN pin of Arduino MKR and  nano.

**Comment by wuehr1999** [comment]
Hi @generationmake 
I changed the +5V rail. Anything else?

**Comment by generationmake** [comment]
I would also add a little capacitor for decoupling reasons on BEMF12 and BEMF34.

IC U5A and U8A have the same function: generating reference voltage. So one of them could be removed. I would also add a capacitor on the voltage.

The signal on the servo outputs have only 3.3V level but I think this is OK.

**Comment by wuehr1999** [comment]
Good morning @generationmake 

I added the capacitors You suggested.

It is on purpose that every back emf measurement circuit has a seperate reference voltage: If You want to use the motors for different tasks, maybe different reference voltages are required. For example if You know the turning direction of the motor, You can get more precise measurements by setting Vref higher or lower and readjusting the gain.

I know that 3.3V for the servo signal is fine from previous projects.

**Comment by generationmake** [comment]
The value of the capacitors C48 and C49 on signal BEMF12 and BEMF34 seems a little bit to high. I think 100 pF or 1 nF would be more appropriate. 

But schematic and layout are OK and I think the board will work. good work!

**Comment by wuehr1999** [comment]
Hi @generationmake 
I changed the capacitor values for the BEMF traces, improved the silkscreen and also squeezed in 4 SMD LEDs for debugging.
As the first version is ready now, I will merge the dev_v0.1 branch into master and order the pcb.

**Pull request closed without merging**
